branch_protections:
  main:
    requires_pull_request: true
    required_reviews: 1
    required_status_checks:
      - make check
      - make fmt
    allow_force_pushes: false
    enforce_conventional_commits: true
conventional_commits:
  enabled: true
required_reviews:
  count: 1
security:
  dependency_audits:
    - pip-audit
    - composer audit
  secrets: no plaintext secrets committed
  commit_signing: recommended
