# Default settings applied to all channels
defaults:
  thread_per_event: false

# Per-guild overrides
# Replace the IDs below with your guild and channel IDs
# guilds:
#   "123456789012345678":
#     thread_per_event: true
#     channels:
#       "234567890123456789":
#         attendee_sample: 5

telegram_bridge:
  mappings:
    "-1001234567890": "234567890123456789"
    # For messages subscriptions, DMs from FetLife will also be sent to the
    # Telegram chat mapped to the Discord channel.
