version: '3.9'

services:
  db:
    image: postgres:15@sha256:0de3e43bbb424d5fb7ca1889150f8e1b525d6c9fbaf9df6d853dcbc2ed5ffa1e
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  adapter:
    build:
      context: .
      dockerfile: adapter/Dockerfile
    env_file: .env
    environment:
      ADAPTER_AUTH_TOKEN: ${ADAPTER_AUTH_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
    deploy:
      update_config:
        order: start-first
        monitor: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file: .env
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      ADAPTER_AUTH_TOKEN: ${ADAPTER_AUTH_TOKEN}
      ADAPTER_BASE_URL: ${ADAPTER_BASE_URL}
    depends_on:
      adapter:
        condition: service_healthy
      db:
        condition: service_healthy
    command: ["python3", "-m", "bot.main"]
    restart: unless-stopped
    deploy:
      update_config:
        order: start-first
        monitor: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
