version: '3.9'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  adapter:
    build:
      context: .
      dockerfile: adapter/Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file: .env
    depends_on:
      - adapter
      - db
    command: ["python3", "bot/main.py"]

volumes:
  db_data:
