#!/bin/sh
msgfile="$1"
msg="$(cat "$msgfile")"
if ! grep -Eq '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: ' "$msgfile"; then
  echo "Commit must follow Conventional Commits. e.g., 'feat(parser): add XYZ'" >&2
  exit 1
fi
